### PR TITLE
[WIP] Cursor highlight

### PR DESCRIPTION
**Pull request by monsieurh**
# purpose
Prettier/clearer menu navigation, instead of outlining the first character of the line, we now 'highlight' the whole line.
[](https://postimg.org/image/3lp18m2xv/)

# implementation
`invert_rect_colors` in `ui.utils` to invert colors on a subset of an image
Modified `SixteenPtView` and `EightPtView` to call the function, and draw the cursor *last*

# status
Tested on emulator
Tested on hardware
 
# issues
Dialog boxes are tight so the cursor rectangle renders badly (some pixels are on the edge and it looks bad:)
[](https://postimg.org/image/lm2tqtctv/)

Adding a 1 pixel padding on the driver side doesn't help much : 
[](https://postimg.org/image/8hx9e62sj/)

any idea ?

### CODE REVIEW

**Comment by CRImier** [comment]
This is a great addition - I thought of something like this, but didn't know how to implement it -
 it drastically improves readability and looks so much more pretty! Thank you, this is a big improvement in terms of UI.

What else uses cursors... Checkboxes, dialog boxes, UI input elements. Sidenote - do you want me to cherry-pick the new canvas implementation into `devel`, so that we could finally use it without waiting for #8 to be finished? I think it'd be a nice addition, and we could put all these canvas-related functions into our `Canvas` and call them as properties.

**Comment by monsieurh** [comment]
Thanks,
don't bother cherry-picking yet, this is no big deal, we will do the big refactor when #8 merge comes around. 😨

**Comment by CRImier** [comment]
There's a bad thing about the DialogBox-related rewrite portion - you're changing the setCursor function meaning, and how UI elements are supposed to use it. The big picture is:

1. Character-based output is a fallback output mode, which other UI elements rely on - for example, input UI elements do (both of them are broken at the moment, though I see you're working on NumpadInputElement)
2. You're adding fixes that only apply to the graphical output mode
3. You rewrite the character output mode in the driver, instead of moving the view into the DialogBox (which would give us significantly more flexibility in the long run, and would help with #3 ).

The negative consequences are: 
1. it breaks an existing interface which ZPUI has been supporting for a long time 
2. it introduces a graphical display-specific view by changing character display-specific drivers, basically, making a change in the wrong place 
3. while this change is related to #3 , it doesn't actually bring us closer to achieving it - the DialogBox is still not in control of how it's displayed
4. it makes future pyLCI and ZPUI merge (that I'm likely to do at some point in the future) significantly harder 
5. it's going to make the interface less testable, since our tests use the text mode fallback to test whether UI elements work as intended and output data on the screen

I'll take a break now and see if I can quickly introduce view support (with fallbacks) into DialogBox, same way it was done with BaseListUIElements =)

**Comment by CRImier** [comment]
[View support for DialogBox done](https://github.com/ZeroPhone/ZPUI/pull/76/commits/171cfebb1739f33cf46c151a9bf4443b4ec94578)

**Comment by CRImier** [comment]
Merging your work since it's a great improvement already, but feel free to continue it, of course =)

**Comment by monsieurh** [comment]
Thanks, what's missing already ? Checkboxes right ?

**Comment by CRImier** [comment]
Actually, I just checked and Checkboxes work out-of-the-box, because they reuse the same view, the mixin they're using doesn't override rendering functions =) So, if you're interested, you can try converting NumpadCharInput.

**Comment by monsieurh** [comment]
NumcharInput is going to have its own refactoring branch at some point ;) thanks for the heads up!

**Comment by CRImier** [comment]
Yay! Thank you for this work, now the UI looks so much more gorgeous! =)

**Pull request merged**
