### PR TITLE
[Discussion] Using a NumberedMenu as the main menu

### PR DESCRIPTION
**Pull request by CRImier**
Using a menu where entries could be reached by one keypress could drastically accelerate the user interactions inside the main menu. So, the question is - could NumberedMenu be used as-is inside the ZPUI main menu? I've fixed a small bug concerning `set_contents`, and now it can!

Before adding this to the development version, however, I'd like some more input.
* Should we hide the numbers from users? Maybe make them opt-out - or opt-in?
* If we don't, how do we make the numbers look more uniform compared to the apps?

### CODE REVIEW

**Comment by monsieurh** [comment]
I did'nt understand your point numer two ` how do we make the numbers look more uniform compared to the apps?` can you elaborate ?

Also i think at some point the main menu should have icons too

**Comment by CRImier** [comment]
@monsieurh When you open an app from the main menu (with prepend_numbers on), the app won't have numbers visible, so it's kind of a "change of context", I don't know how to put it. I suggest you try it and see for yourself =)

Agree on icons - there would need to be a separate View for those, though (just like there's a MainMenuTripletView, IIRC), and we could enable that for main menu by default once it's done. That's where the viewport would be handy to have, BTW!

**Comment by CRImier** [comment]
So, I've thought about it, and experimented some. It makes sense to have a NumberedMenu as some kind of mixin to a Menu. The reason is - I think that consistency is going to be important, so app menus would need to have numpad navigation by default (otherwise, the "jump" from numpad-based to arrowkey-based navigation once you enter an app is uncomfortable).

**Comment by monsieurh** [comment]
Agreed, should be the default behaviour

**Comment by CRImier** [comment]
Will eventually open as an issue - for now, merged the changes from this branch but `NumberedMenu` is not the main menu.

**Pull request merged**
