### PR TITLE
Added highscores and fixed winning of 2048 game, partially fixes #30

### LINKED ISSUE #30: Improving the 2048 game
The 2048 game (included in `apps/games/g_2048/`) could use some features; namely:

- [ ] A prettier UI - going away from the text-based data output (using `o.display_data()`) and drawing a canvas instead, then passing it to `o.display_image()`.
- [x] Currently, the game can't be continued once 2048 has been reached, it'd be good to allow it (and still acknowledge the endgame as a 'win' once the field is full) (done, thanks to @johanneskool )
- [x] Once the previous feature is done, highscores could be added. (done, thanks to @johanneskool )

### PR DESCRIPTION
**Pull request by johanneskool**
Also formatted the code according to best practices.

### CODE REVIEW

**Comment by johanneskool** [comment]
I removed that 512, it was a debugging value. The path is now correctly determined.

**Comment by CRImier** [comment]
No need to set `local_path` to an attribute of the game class, regardless, it technically works, I guess? =D Thank you, merging!

**Comment by johanneskool** [comment]
That way I don't have to redefine it in write_score(), or can that be done another way?

**Comment by CRImier** [comment]
Usually, you can just add it at the top of the file, globally, so that other classes can use it.

**Pull request merged**
